version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    restart: "always"
    ports:
      - "27017:27017"
    volumes: 
      - $HOME/.docker/volumes/codeland-mongo:/data/db 
  mysql:
    container_name: mysql
    image: mysql:8.0.21
    restart: "always"
    ports:
      - "3306:3306"
    command:
      - "--bind-address=0.0.0.0"
    volumes:
        - $HOME/.docker/volumes/codeland-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  postgres:
    container_name: postgresql
    image: postgres:13-alpine
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - $HOME/.docker/volumes/codeland-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      
