version: "2"
services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    restart: "always"
    ports:
      - "27017:27017"
    volumes: 
      - $HOME/.docker/volumes/codeland-mongo:/data/db 
  mysql:
    container_name: mysql
    image: mysql:8.0.21
    restart: "always"
    ports:
      - "3306:3306"
    command:
      - "--bind-address=0.0.0.0"
    volumes:
        - $HOME/.docker/volumes/codeland-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
  postgres:
    container_name: postgresql
    image: postgres:13-alpine
    restart: "always"
    ports:
      - "5432:5432"
    volumes:
      - $HOME/.docker/volumes/codeland-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
  neo4j:
    container_name: neo4j
    image: neo4j:3.5.3
    restart: "always"
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - $HOME/.docker/volumes/codeland-neo4j/data:/data
      - $HOME/.docker/volumes/codeland-neo4j/logs:/logs
      - $HOME/.docker/volumes/codeland-neo4j/import:/var/lib.neo4j/import
      - $HOME/.docker/volumes/codeland-neo4j/plugins:/plugins
    environment:
      # uncomment next three lines if running docker on windows
      #NEO4J_dbms_connector_http_advertised__address: "localhost:7474"
      #NEO4J_dbms_connector_bolt_advertised__address: "localhost:7687"
      NEO4J_AUTH: neo4j/password
  
